### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by lehtoneo** [Jonkke/ot-harkkatyo#1]
Pakkausrakenne
- Mielestäni hyvä ja selkeä

Clean Code
- Jotkut metodien parametrit voisi nimetä hieman paremmin, esimerkiksi kaikki GameStateService sekä SceneDirectorService oliot on nimetty vain "gss" tai "sds", joka tekee koodista hieman raskasta lukea. Toki koodin ymmärtää myös tämänhetkisillä nimillä.
- Luokat ja metodit ovat hyvin nimettyjä.
- Luokat huolehtii hyvin vain yhdestä asiasta, sovelluslogiikka eriytetty käyttöliittymästä
- Ball luokan metodi update on jokseenkin pitkä, sitä voisi ehkä hieman "pätkiä" useammiksi metodeiksi
- Menu scenen addMenu metodin voisi ehkä jakaa neljään metodiin: jokaisessa näistä neljästä metodissa alustettaisiin yksi "menuItem".

Pieni "bugi" ohjelmassa:
- Kun avaan ohjelman fuksiläppärilläni (vm. 2017), peli ei mahdu ruudulleni, sillä pelinäkymä on hieman liian korkea (näkymän kokoa ei pysty ainakaan minun koneellani myöskään muuttamaan). 
- Bugin voisi korjata pienentämällä pelinäkymän oletuskokoa (duh)
- Toisaalta se, että pelinäkymän kokoa pystyisi muokkaamaan itselle/näytölle sopivaksi, olisi vielä parempi korjaus

Kaiken kaikkiaan hyvää työtä!

**Comment by lehtoneo** [comment]
Ainiin, issuesta puuttui harjoitustyön lataamisaika. Latasin harjoitustyön 24.4 klo 16.

**Comment by ghost** [comment]
Kiitos, hyviä huomioita!
